spring.application.name=SpringBootCore
#paymentGateway.type=razorpay
#paymentGateway.retryCount=3

payment-property.type=paytm
payment-property.retry-count=3
payment-property.enabled=true
payment-property.timeout=6000